name = "PlaceholderName"
author = "jmavd"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3df957d9e962b15d482b40e4d70222704cefe758275b163df22a3d3aa08c8be"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0-beta.1"
