name = "CapMC"
author = "JMavDean"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a708249e5a44b1712cfcdad2f646191cdd64f964c1fe51b3ea18b33030db70ab"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
