name = "CapMC"
author = "JMavDean"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c571d7212a28b6ae271985097f5083ee2366f6bfe10247972eb2ea39680a119"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
