name = "CapMC"
author = "JMavDean"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68a2d93c19f3092ee19d88caf9fdb13faf2e506ee5c29b140774fa2d6c2890d0"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
