name = "CapMC"
author = "JMavDean"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c4b1eab22e8b8244df91c800403a7a3a1d5a4ea24e7cb41bc9ee0acd98b000d"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
