name = "CapMC"
author = "JMavDean"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d7d581eec09b3ebddd3b01dfe22c951f9c61a985d78b114698ade70b8c401e6"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
