name = "CapMC"
author = "JMavDean"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdd59934d08e54a763505ff27c136ff054815c71cffbb9cdd24554af1ab8b949"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
